### PR TITLE
Add CS 2 Support

### PR DESCRIPTION
**Pull request by 810**

### CODE REVIEW

**Comment by 810** [comment]
Please create a new branch for CS2. So we can move to the newest versions.

**Comment by jatitoam** [comment]
We are actually discontinuing this repository, since we now have https://github.com/joomla-projects/joomla-testing-robo which contains more tasks

In this branch (https://github.com/joomla-projects/joomla-testing-robo/tree/container-test) I'm adding CS2 support via @nibra's package.

I just noticed that @yvesh commented in Jorobo that the package is outdated.

**Comment by 810** [comment]
@jatitoam thnx, will close this one, could you change the description from this rep, to abandoned.

**Comment by jatitoam** [comment]
Yeah, will do :)

**Pull request closed without merging**
